<h2>Informatie</h2>
<p>Wij zijn een middelgroot zelfstandig werkzaam accountantskantoor en al bijna 50 jaar werkzaam in de regio Eemland. Als AA-Accountant zijn wij gespecialiseerd in het midden- en kleinbedrijf en hechten veel waarde aan persoonlijk contact.</p>
<p>Onze dienstverlening bestaat onder andere uit:</p>
<ul>
  <li>het samenstellen, beoordelen of controleren van uw jaarrekening;</li>
  <li>het inrichten en/of voeren van uw administratie;</li>
  <li>het opstellen van een accountantsrapport met bijbehorende analyses en adviezen;</li>
  <li>assistentie bij uw automatiseringsplannen;</li>
  <li>het verzorgen van uw salarisadministratie;</li>
  <li>het verzorgen van tussentijdse verslaglegging;</li>
  <li>assistentie bij het opstellen van een begroting en bewaking hiervan;</li>
  <li>het verzorgen van uw aangifte inkomstenbelasting, omzetbelasting, loonbelasting, dividendbelasting en/of vennootschapsbelasting;</li>
  <li>begeleiding bij het opstellen van uw financi&#235;le planning op langere termijn;</li>
  <li>advisering inzake de keuze van de rechtsvorm (eenmanszaak, v.o.f., besloten vennootschap);</li>
  <li>advisering bij bedrijfsopvolging of bedrijfsovername;</li>
  <li>het vervullen van een klankbordfunctie voor uw beleid etc.;</li>
  <li>assistentie bij het opstellen van een ondernemingsplan;</li>
</ul>
<h3>Bent u ge&#239;nteresseerd?</h3>
<p>Bel of <a href="mailto:info@dejongaccountants.nl">e-mail</a> om vrijblijvend een afspraak te maken voor een kennismakingsgesprek.</p>