<h2>Links</h2>
<p>Hier vindt u links naar allerlei interessante websites.</p>
<h3>Op de sociale media:</h3>
<ul>
  <li><a href="http://www.facebook.com/pages/De-Jong-Accountants-en-Belastingadviseurs/177096265656584" target="_blank">Volg ons op Facebook</a></li>
  <li><a href="http://www.linkedin.com/company/de-jong-accountants-en-belastingadviseurs" target="_blank">Volg ons op LinkedIn</a></li>
</ul>
<h3>Enkele verenigingen die door ons worden gesponsord:</h3>
<ul>
  <li><a href="http://www.vvz49.nl/" target="_blank">Voetbalvereniging V.V.Z. '49 te Soest</a></li>
  <li><a href="http://www.so-soest.nl/" target="_blank">Voetbalvereniging S.O. Soest</a></li>
  <li><a href="http://www.vvsec.nl/" target="_blank">Voetbalvereniging SEC</a></li>
  <li><a href="http://www.vv-hees.nl/" target="_blank">Voetbalvereniging Hees</a></li>
  <li><a href="http://www.stamsovoco.nl/" target="_blank">Volleybalvereniging StamSovoco</a></li>
  <li><a href="http://www.mhcsoest.nl/" target="_blank">Mixed Hockey Club Soest</a></li>
</ul>
