<h2>Vacatures</h2>
<p>Op dit moment hebben wij een vacature voor de functie van:</p>
<h3>SALARISADMINISTRATEUR (M/V), 24 UUR</h3>
<p><strong>Werkzaamheden</strong><br/>
Als salarisadministrateur verricht je in teamverband zelfstandig werkzaamheden op het gebied van salarisadministraties. Je verzorgt de gehele salarisadministratie voor klanten en bereidt adviezen voor. Mede door jouw professionaliteit verloopt het hele verwerkingsproces vlekkeloos. Uiteraard heb je regelmatig contact met je klanten en betrokken instanties. 
Je volgt de ontwikkelingen op ons vakgebied nauwgezet en informeert onze klanten hierover.</p>
<p><strong>Wie zoeken wij?</strong><br/>
Voor deze functie zijn wij op zoek naar een kandidaat met enige jaren relevante werkervaring. Je beschikt over een MBO werk- en denkniveau. Verder heb je een PDL diploma, dan wel ben je bereid dit te behalen.<br/>
Samenwerken in een team gaat je goed af en je kunt het overzicht behouden in de dagelijkse werkzaamheden. Ambitie en flexibiliteit zijn voor jou geen onbekende eigenschappen. Kennis van het salarispakket Unit4 Salaris is een pré.</p>
<p><strong>Wat bieden wij?</strong><br/>
Uiteraard bieden wij, naast een goede werksfeer, een goed salaris met pensioenopbouw en secundaire arbeidsvoorwaarden overeenkomstig leeftijd, opleiding en ervaring.</p>
<p>Enthousiaste en gemotiveerde kandidaten verzoeken wij hun sollicitatie voorzien van c.v. te richten aan:</p>
<p>dhr. R.J. de Jong, Postbus 3139, 3760 DC Soest<br/>
of e-mail: <a href="mailto:info@dejongaccountants.nl">info@dejongaccountants.nl</a></p>
<p><em>Acquisitie n.a.v. deze advertentie wordt niet op prijs gesteld.</em>
