<h2>Vacatures</h2>
<p>Op dit moment hebben wij een vacature voor de functie van:</p>
<h3>ASSISTENT-ACCOUNTANT (M/V)</h3>
<p>Van hem of haar wordt verwacht dat hij of zij zich nu of in de toekomst gaat bezighouden met de volgende kerntaken van ons kantoor:</p>
<ul>
  <li>het samenstellen, beoordelen of controleren van jaarrekeningen;</li>
  <li>het inrichten en/of voeren van financi&#235;le- en salarisadministraties;</li>
  <li>het verzorgen van fiscale aangiften voor ondernemers en particulieren;</li>
  <li>advisering omtrent o.a. starten van een onderneming, bedrijfsopvolging, keuze rechtsvorm;</li>
  <li>het vervullen van een klankbordfunctie voor de ondernemer.</li>
</ul>
<p>Van de kandidaten verwachten wij dat zij een opleiding op SPD/HEAO-niveau hebben met enkele jaren ervaring in een accountancypraktijk of soortgelijke omgeving.</p>
<p>Uiteraard bieden wij, naast een goede werksfeer, een goed salaris met pensioenopbouw en secundaire arbeidsvoorwaarden overeenkomstig leeftijd, opleiding en ervaring.</p>
<p>Enthousiaste en gemotiveerde kandidaten verzoeken wij hun sollicitatie voorzien van c.v. te richten aan:</p>
<p>dhr. R.J. de Jong, Postbus 3139, 3760 DC Soest<br/>
of e-mail: <a href="mailto:info@dejongaccountants.nl">info@dejongaccountants.nl</a></p>
<p><em>Acquisitie n.a.v. deze advertentie wordt niet op prijs gesteld.</em>
