<h2>Vacatures</h2>
<p>Op dit moment hebben wij een vacature voor de functie van:</p>
<ul>
  <li><a href="./?p=vacatures_assistent">Assistent-accountant (m/v)</a></li>
  <!--li><a href="./?p=vacatures_salarisadmin">Salarisadministrateur (m/v)</a></li-->
</ul>
<p>Enthousiaste en gemotiveerde kandidaten verzoeken wij hun sollicitatie voorzien van c.v. te richten aan:</p>
<p>dhr. R.J. de Jong, Postbus 3139, 3760 DC Soest<br/>
of e-mail: <a href="mailto:info@dejongaccountants.nl">info@dejongaccountants.nl</a></p>
<p><em>Acquisitie n.a.v. deze advertentie wordt niet op prijs gesteld.</em>
